version: '3'
services:
  webapp:
    build: .
    ports:
      - "4000:3000"
    container_name: "webapp-1"
    environment:
      - MONGO_URL=mongodb://mongo:27017/its
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
